select a.PRODUCT_ID,a.PRODUCT_NAME, sum(a.PRICE * b.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT a, FOOD_ORDER b
where a.PRODUCT_ID = b.PRODUCT_ID AND DATE_FORMAT(b.PRODUCE_DATE,"%Y-%m") = '2022-05'
group by a.PRODUCT_NAME
order by TOTAL_SALES DESC, a.PRODUCT_ID