select TITLE,a.BOARD_ID,REPLY_ID,b.WRITER_ID,b.CONTENTS,DATE_FORMAT(b.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE
from USED_GOODS_BOARD a,USED_GOODS_REPLY b
where a.BOARD_ID = b.BOARD_ID AND DATE_FORMAT(a.CREATED_DATE,"%Y-%m") = '2022-10'
order by b.CREATED_DATE,a.TITLE